// External libraries
global using System.Reflection;
global using Carter;
global using Npgsql;
global using FluentValidation;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Any;
global using Microsoft.OpenApi.Models;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Swashbuckle.AspNetCore.SwaggerUI;
global using Asp.Versioning.ApiExplorer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Linq.Expressions;
global using System.Data;
global using Dapper;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using StackExchange.Redis;
global using Microsoft.IdentityModel.Tokens;
global using Minio;
global using Minio.DataModel.Args;

// Project namespaces
global using netflix_clone_media.Api.Enums;
global using netflix_clone_media.Api.DependencyInjection.Options;
global using netflix_clone_media.Api.DependencyInjection.Extensions;
global using netflix_clone_media.Api.Persistence;
global using netflix_clone_media.Api.Settings;
global using netflix_clone_media.Api.Persistence.Entitiy;
global using netflix_clone_media.Api.DTOs;
global using netflix_clone_media.Api.Endpoints.Requests;
global using netflix_clone_media.Api.Persistence.Repositories;
global using netflix_clone_shared;
global using netflix_clone_shared.Entities;
global using netflix_clone_shared.Mediator;
global using netflix_clone_shared.Middlewares;
global using netflix_clone_shared.Idempotence;
global using netflix_clone_shared.CQRS;
global using netflix_clone_shared.Results;
global using netflix_clone_shared.Messages;
global using netflix_clone_shared.Exceptions;
global using netflix_clone_shared.RequestContext;

